#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 14 20:06:33 2018

@author: Julie
"""

#%%

import math
math.pi
#%%
def volume_cilinder (radius, height):
    return (radius * radius * math.pi) * height

#%%
def volume_sphere (radius):
    return radius**3 * math.pi * 3/4

#%%
def volume_cilinder2 ():
    radius = float(input("What is the radius of the cilinder? "))
    height = float(input("What is the height of the cilinder? "))
    return (math.pi * radius**2) * height

print ("The volume of the cilinder is " + str(volume_cilinder2()))

#%%
def volume_sphere2  ():
    radius = float(input("What is the radius of the sphere? "))
    return radius**3 * math.pi * 3/4

print ("The volume of the sphere is " + str(volume_sphere2()))

#%%
import matplotlib.pyplot as plt
import numpy as np
grades = ["pass", "proficiency", "excellence", "honors"]

plt.bar(grades, [15,35,35,15])